# TODO: this config runs REALLY slow right now??

cpu:
  init_pc: reset
  clock_speed: 1000000

ram:
  # 8K
  - start: 0
    size: 8192
  # # 16K
  # - start: 8192
  #   size: 8192
  # # 32K
  # - start: 16384
  #   size: 16384

roms:
  - file: roms/pet2001/c000-basic1.bin
    start: 0xc000
    ro: true # this is the default

  - file: roms/pet2001/d000-basic2.bin
    start: 0xd000

  - file: roms/pet2001/e000-editor.bin
    start: 0xe000

  - file: roms/pet2001/f000-kernal.bin
    start: 0xf000

plugins:
  enumerate: false
  config:
    - file: 6520-pia.so
      address: 0xe810

    - file: 6520-pia.so
      address: 0xe820

    - file: 6522-via.so
      address: 0xe840

    - file: pet2001.so
      # disable: false
      address: 0x8000
